### ISSUE TITLE
Was unable to import new publication to BMDB, until I started creating this bug report, and then it worked. Of course.

### ISSUE THREAD

**Issue by mryan4** [EDRN/biomarker-database#23]
## 🐛 Describe the Bug

Using the Import a new publication feature on the Publications tab gave an error.  Error is the same in both Firefox and Chrome. See attached screenshots.

However, as I created this bug report and tried to import this publication for the third time, in order to take another screenshot, IT WORKED. 

So I'm sending you this bug report in case you want to know about a bug that occurred, and then disappeared. I don't need you to do anything, I guess this is just for documentation. 

## 📜 How To Reproduce

Put steps to reproduce the behavior here, **including URLs**, such as
1. Go to the page for ApoAII-ATQ/AT, a new biomarker that I just created today
https://bmdb.jpl.nasa.gov/biomarkers/view/1240

2. Go to Publications tab
https://bmdb.jpl.nasa.gov/biomarkers/publications/1240

3. Click on Add a Publication, then click on Import a new publication

4. Paste the PMID I am trying to import: 26549697, click on Request.

## 🖼 Screenshots

Screenshots of the error message that occurred in both Chrome and Firefox:

![Screen Shot 2020-10-14 at 9 25 11 AM](https://user-images.githubusercontent.com/68615089/95996455-aec70700-0e00-11eb-9d3b-a67343d809de.png)

![Screen Shot 2020-10-14 at 9 23 45 AM](https://user-images.githubusercontent.com/68615089/95996651-ecc42b00-0e00-11eb-826c-07019ab85d1c.png)

## 🕵️‍♀️ Extra Details

But the whole thing is moot now, because the import worked when I started creating this bug report and went through all the steps again to make sure I was giving you all the URLs and screenshots that you needed.

**Comment by nutjob4life** [comment]
@mryan4 I'm going to tentatively close this based on the fact that the [EDRN Portal](https://github.com/EDRN/P5) has also been struggling to do its nightly ingest because of issues with querying the Entrez EUtils PubMed database. It's been incredibly unreliable lately, giving errors to complex search queries or even simple retrievals of a single publication for an already-known PubMed ID number. These are of course beyond our control (and perhaps we can and should spend some time cleaning up our error handling). But the short-term hope is that PubMed will get better soon! Maybe it's just Covid-19? 🤷‍♀️
