### ISSUE TITLE
SQL window

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/biomarker-database#41]
## 🤔 Tell Us About the Feature

Provide an SQL access for @mryan4 in the Focus BMDB interface.

## 🎇 What Solution You'd Like

Maybe a way to execute SQL (but read only!)

## 〽️ Alternative Ideas

@dcrichto suggests Google Sheets.

**Comment by nutjob4life** [comment]
@mryan4 do you have JPL VPN? The system admins may wish to seal this particular feature off to those only with VPN.

**Comment by mryan4** [comment]
Yes, I do. Phew!

**Comment by nutjob4life** [comment]
@mryan4 okay, I've configured and deployed "phpMyAdmin" and it's ready to use for the Biomarker Database! Rather than home-brew a SQL entry-window solution, this one has all the bells and whistles that should make exploring the data, paging through tables, creating complex queries, exporting to spreadsheets, and even more possible. You can give BMDB the "third degree" with this! 👮

To access it, you will need:

- JPL VPN
- The database username `biobrowse`¹ and password²
- The URL to access it: https://bmdb.jpl.nasa.gov/3rd-degree/

If you want to schedule a time to go over the features, let me know. I'm happy to help explore it.

¹The `biobrowse` username has read-only access, so don't worry about messing anything up³
²The password will come under a plain brown wrapper
³If you do want to be able to do mass updates and want a read+write account, let me know

**Comment by mryan4** [comment]
Hi Sean,

Thank you!  I’ll take a look at it tomorrow. This will be great. 

I’m sure I will definitely need some help with queries, so I will accept your offer to go over it.  I’m open pretty much any time Thursday or Friday.  Let me know what works for you.

Maureen


Maureen Ryan
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Apr 21, 2021, at 3:17 PM, Sean Kelly ***@***.***> wrote:


@mryan4 <https://github.com/mryan4> okay, I've configured and deployed "phpMyAdmin" and it's ready to use for the Biomarker Database! Rather than home-brew a SQL entry-window solution, this one has all the bells and whistles that should make exploring the data, paging through tables, creating complex queries, exporting to spreadsheets, and even more possible. You can give BMDB the "third degree" with this! 👮

To access it, you will need:

JPL VPN
The database username biobrowse¹ and password²
The URL to access it: https://bmdb.jpl.nasa.gov/3rd-degree/ <https://bmdb.jpl.nasa.gov/3rd-degree/>
If you want to schedule a time to go over the features, let me know. I'm happy to help explore it.

¹The biobrowse username has read-only access, so don't worry about messing anything up³
²The password will come under a plain brown wrapper
³If you do want to be able to do mass updates and want a read+write account, let me know
